apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: app-nginx
  name: nginx-replicaset
spec:
    replicas: 3
    selector:
      matchLabels:
        app: app-nginx
    template:
      metadata:
        labels:
          app: app-nginx
      spec:
        containers:
        - image: nginx:1.18.0
          name: nginx
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests:
              cpu: 0.3
              memory: 128Mi

