apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: teste
  name: teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teste
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: teste
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
