apiVersion: v1
kind: Pod
metadata:
  labels:
    run: exerc
  name: exerc
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
      - mountPath: /nginxempty
        name: nginx-emptydir
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
          cpu: "0.3"
          memory: "64Mi"
  - image: ubuntu
    name: ubuntu
    volumeMounts:
      - mountPath: /ubuntuempty
        name: ubuntu-emptydir
    args:
      - sleep
      - "1800"
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: nginx-emptydir
    emptyDir:
      sizeLimit: 265Mi
  - name: ubuntu-emptydir
    emptyDir:
      sizeLimit: "265Mi"

